### ISSUE TITLE
configuredObjects.deployment.includes is not a function

### ISSUE THREAD

**Issue by PierrickLozach** [Kamshak/deployment-tool#1]
Just used your tool (thanks btw!!) but I am getting an error: `[TypeError: configuredObjects.deployment.includes is not a function]`

pods are deployed but I am not sure why there is an error at the end. Here is what I run:

```
$ cat deployment.yaml | node ../../index.js
Calling kubectl to apply changes...
[KUBECTL] deployment/ping
[KUBECTL] service/ping
Waiting until deployments ping have been applied.
All deployments have been rolled out. Fetching changes...
[TypeError: configuredObjects.deployment.includes is not a function]
```

deployment.yaml:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ping
  name: ping
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        imagePullPolicy: Always
        image: pierrickl/commucheck-ping:0.0.4
        readinessProbe: # Check when application is ready
          httpGet:
            path: "/api/v1/ping?host=www.google.com&log=false&event=false"
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe: # healthcheck every 60 seconds
            httpGet:
              path: "/api/v1/ping?host=www.google.com&log=false&event=false"
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 60
        ports:
        - containerPort: 3000
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ping
  name: ping
spec:
  ports:
    - port: 3000
      name: service
  selector:
    app: ping
```

Could you let me know what is causing that error?
